name: SurvivalGames
main: SurvivalGames\SurvivalGames
version: 1.0.0
api: 1.13.0
author: HotFireyDeath

commands:
    sg:
        description: Survival Games core command.
        usage: /sg
        permission: sg.main