name: FactionsPlugin
main: FactionsPlugin\FactionsPlugin
version: 1.0.0
api: 2.0.0
author: HotFireyDeath/Chopstick Software

commands:
    f:
        description: Factions command.
        usage: /f
        permission: FactionsPlugin.main
---
