#ServerAuthPlus configuration file..

chatauthenticate: on
#authenticate in the chat, similar to the extension SimpleAuthHelper.

limitchars: on
#Strictly limit passwords to 0-9, a-z, A-Z.

emailauth: on
#IMPORTANT: This uses the php's mail() function. Please confirm
#you have a mail webserver setup.

#Requires client email input, sends a confirmation email;
#with the below content:

emailauthcontent:
#Use {player} for player's name.
- "Welcome to my server, {player}!"
- " "
- "Thanks for joining my server! This email is to notify you that you've registered!"
- "So, be sure to have fun, and thanks for registering."
- " "
- "This email was sent using ServerAuthPlus."