name: FileBrowser
main: FileBrowser\FileBrowser
version: 1.0.0
api: 1.13.0
author: HotFireyDeath/Chopstick Software

commands:
 filebrowser:
  description: The command for FileBrowser.
  usage: /filebrowser
  permission: filebrowser.main
