name: TimeZones
main: TimeZones\TimeZones
version: 3.0
api: 1.13.0
author: HotFireyDeath/Chopstick Software

commands:
    tz:
        description: TimeZones command.
        usage: /tz
        permission: timezones.main