name: HalloweenPM
main: HalloweenPM\HalloweenPM
version: 1.0.0
api: 1.0.0
author: HotFireyDeath

commands:
  frankenstein:
    description: Talk like frankenstein. Scary!
    permission: HalloweenPM.Frankenstein
    usage: /frankenstein <msg>
  death:
    description: Talk like Death. Scary too!
    permission: HalloweenPM.Death
    usage: /death <msg>
  candy:
    description: Remember, give some to your friends!
    permission: HalloweenPM.Candy
    usage: /candy <give:eat:buy:have?> <type>
  zombie:
    description: Arrrggg... talk like a zombie!
    permission: HalloweenPM.zombie
    usage: /zombie <msg>
  pumpkin:
    description: Talk to your friends in a pumpkinized manner.
    permission: HalloweenPM.pumpkin
    usage: /pumpkin <msg>
  
