Corrector: 2

#Colors are currently as stated:
    #Blue
    #Red
    #Green
    #Aqua
    #Yellow
    #White
    #Gray
    #Purple
    #Black
    #Plain
    
    #please spell them as-is for functionality to work.
    
    
Color: Blue
