#HolidayPM Configuration File

version: MS4wLjA=
#Do not touch this option, this is used for plugin updating purposes.

holiday_mode: auto
#holiday_mode = How will holidays be toggled?
#options: {auto (holidays will automatically be toggled by the plugin, hassle-free), 
#manual (you manually select the active holiday)}

timezone: EST
#timezone = Your timezone! Seriously recommend to set if holiday_mode is auto!

#If holiday_mode is set to manual, please change these toggles as needed.
new_year: off
christmas: off
day_of_the_dead: off
chinese_new_years: off
valentines: off
st_patricks: off
independence_day: off
halloween: off
hanukkah: off
thanksgiving: off
#If you have made a custom holiday, you will find it's options in the plugin folder.#

server_name: Minecraft PE Server
#server_name = Your name of your server, used for plugin broadcasts, etc