name: HolidayPM
main: HolidayPM\HolidayPM
version: 1.0.0-2016
api: 1.0.0
author: HotFireyDeath/Chopstick Software

commands:
    holidaypm:
        description: HolidayPM core command.
        usage: /holidaypm
        permission: HolidayPM.main