#FactionsPlugin configuration file (at version 1.0.0)

land:
    officers_only: true
    #Only officers/owners can claim land?
    claim_power_cost: 1
    #Amount of "power" to deduct from faction.
    claimsize: 5
    #Distance of your land (x/z).
    blockFromWalking: true
    #Blocks other faction members from walking in claimed lands.
    notifyLand: true
    #Notifies you of which land you are inside.
general:
    officers_invite: true
    #Only officers/owners can invite?
    officers_promote: true
    #Only officers/owners can promote?
    officers_demote: true
    #Only officers/owners can demote?
misc:
    updateSaveNotify: true
    #Displays in console when save file(s) are updated.
---
