#FactionsPlugin configuration file (at version 1.0.0)

land:
    claim_power_cost: 1
    #Amount of "power" to deduct from faction.
    claimsize: 5
    #Distance of your land (x/z).
    blockFromWalking: true
    #Blocks other faction members from walking in claimed lands.
    notifyLand: true
    #Notifies you of which land you are inside.
   
misc:
    updateSaveNotify: true
    #Displays in console when save file(s) are updated.
---
