name: TapCommand
main: TapCommand\TapCommand
version: 1.0.0
api: 1.13.0
author: HotFireyDeath/Chopstick Software

commands:
    tc:
        description: TapCommand main command.
        usage: /tc
        permission: tc.main